// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://acaqdhlabhapnjcehczi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjYXFkaGxhYmhhcG5qY2VoY3ppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MzI4OTMsImV4cCI6MjA3MzUwODg5M30.1sprophDyQ4ZmFJc5dsFLf_K2PdMm3e9w_B0kJYWWr4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});